### ISSUE TITLE
NameError: wrong constant name INFO 

### ISSUE THREAD

**Issue by sergio-ns** [standardnotes/syncing-server#155]
Hello,
I got this error message in the log file of the docker container of syncing-server.

The error goes away and the container runs after commenting out the apparently offending line in the .env file:
#RAILS_LOG_LEVEL=info # "debug" | "info" | "warn" | "error" | "fatal"

See below for the complete log.
Thanks
S.

Prestart Step 1/3 - Removing server lock

Prestart Step 2/3 - Migrating database

rake aborted!

NameError: wrong constant name INFO 

/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application/bootstrap.rb:61:in `const_get'

/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application/bootstrap.rb:61:in `block in <module:Bootstrap>'

/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'

/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'

/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'

/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'

/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'

/syncing-server/config/environment.rb:5:in `<main>'

/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'

/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'

/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'

/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application.rb:337:in `require_environment!'

/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application.rb:520:in `block in run_tasks_blocks'

/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'

/usr/local/bundle/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'

/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'

/usr/local/bundle/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'

/usr/local/bundle/bin/bundle:23:in `load'

/usr/local/bundle/bin/bundle:23:in `<main>'

Tasks: TOP => db:migrate:ignore_concurrent => environment

(See full trace by running task with --trace)

**Comment by karolsojko** [comment]
Hey @sergio-ns I did run on a fresh copy:

```
cp .env.sample .env
docker-compose build
docker-compose up
```
No errors - can you share some steps to reproduce this?

**Comment by sergio-ns** [comment]
Hello,
I just stopped and removed my standard-sync docker container and recreated it in order to reproduce the error.
This is how get the container up and running:

`#!/bin/sh
docker run -d -p 3000:3000 \
--name "standard_notes_sync" \
--env-file=standard_notes_sync_env \
--network=keplernet \
--restart always \
standardnotes/syncing-server:stable
`

My env file is (I uncommented out the problem line):

# Sample ENV setup Variables
# Copy this file and update as needed.
#
#   $ cp .env.sample .env
#
# Do not include this new file in source control
#

# Rails Settings
EXPOSED_PORT=3000
# change this to "production" for production use, otherwise the access token time is very short and forces re-login
RAILS_ENV=production
RAILS_LOG_TO_STDOUT=false

**RAILS_LOG_LEVEL=info # "debug" | "info" | "warn" | "error" | "fatal"**

#SQS_QUEUE=somequeue
#SQS_QUEUE_LOW_PRIORITY=low_priority_queue
#AWS_REGION=us-west1
#S3_BACKUP_BUCKET_NAME=

ACTIVE_JOB_QUEUE_ADAPTER=async

# Database Settings
DB_PORT=mysql-port
DB_HOST=mysql-ip-address
DB_DATABASE=mysql-sn-db
DB_USERNAME=mysql-user
# Please change this!
DB_PASSWORD=mysql-pass
DB_POOL_SIZE=30
DB_WAIT_TIMEOUT=180

# Secrets
# Use: "bundle exec rake secret" or "openssl rand -hex 64"
# To generate required secret key base below

SECRET_KEY_BASE= (key removed)
PSEUDO_KEY_PARAMS_KEY= (key removed)

# Disable user registration
#DISABLE_USER_REGISTRATION=true

# Datadog
DATADOG_ENABLED=false

# Mailer settings
SMTP_HOST=my smpt host (google)
SMTP_PORT=587
SMTP_USERNAME= my smpt username
SMTP_PASSWORD= my app password


And syncing-server complains again about the name of the constant:

2021-01-04T11:58:21.229767251Z Prestart Step 1/3 - Removing server lock
2021-01-04T11:58:21.234092510Z Prestart Step 2/3 - Migrating database
2021-01-04T11:58:25.381400337Z rake aborted!
2021-01-04T11:58:25.381535262Z NameError: wrong constant name INFO # "DEBUG" | "INFO" | "WARN" | "ERROR" | "FATAL"
2021-01-04T11:58:25.381687635Z /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application/bootstrap.rb:61:in `const_get'
2021-01-04T11:58:25.381700877Z /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application/bootstrap.rb:61:in `block in <module:Bootstrap>'
2021-01-04T11:58:25.381710891Z /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
2021-01-04T11:58:25.381719665Z /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
2021-01-04T11:58:25.381728347Z /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
2021-01-04T11:58:25.381740322Z /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
2021-01-04T11:58:25.381769352Z /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
2021-01-04T11:58:25.381778657Z /syncing-server/config/environment.rb:5:in `<main>'
2021-01-04T11:58:25.381788334Z /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
2021-01-04T11:58:25.381797057Z /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
2021-01-04T11:58:25.381805623Z /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
2021-01-04T11:58:25.381814061Z /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
2021-01-04T11:58:25.381822581Z /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
2021-01-04T11:58:25.381840515Z /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
2021-01-04T11:58:25.381851567Z /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
2021-01-04T11:58:25.381860131Z /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
2021-01-04T11:58:25.381868556Z /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application.rb:337:in `require_environment!'
2021-01-04T11:58:25.381877089Z /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application.rb:520:in `block in run_tasks_blocks'
2021-01-04T11:58:25.381885399Z /usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
2021-01-04T11:58:25.381893885Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
2021-01-04T11:58:25.381902211Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
2021-01-04T11:58:25.381911809Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
2021-01-04T11:58:25.381920720Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
2021-01-04T11:58:25.381929123Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2021-01-04T11:58:25.381937494Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
2021-01-04T11:58:25.381945951Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
2021-01-04T11:58:25.381954266Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
2021-01-04T11:58:25.381962511Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
2021-01-04T11:58:25.381970813Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
2021-01-04T11:58:25.381979132Z /usr/local/bundle/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
2021-01-04T11:58:25.381987654Z /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
2021-01-04T11:58:25.382001318Z /usr/local/bundle/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
2021-01-04T11:58:25.382010607Z /usr/local/bundle/bin/bundle:23:in `load'
2021-01-04T11:58:25.382018787Z /usr/local/bundle/bin/bundle:23:in `<main>'
2021-01-04T11:58:25.382071327Z Tasks: TOP => db:migrate:ignore_concurrent => environment
2021-01-04T11:58:25.382082980Z (See full trace by running task with --trace)

**Comment by chengs2035** [comment]
me 2
so i try
```
#RAILS_LOG_LEVEL=info
```
fix it.

**Comment by karolsojko** [comment]
Please adjust your env file with the fixes applied in https://github.com/standardnotes/syncing-server/commit/e979405520a575916c4e68cc6689b11e3b3f0766 

Also make sure to switch your Docker image tag so that you are using `standardnotes/syncing-server:latest`
