### ISSUE TITLE
Syncing Server Keeps Restarting (logs below)

### ISSUE THREAD

**Issue by hwittenborn** [standardnotes/syncing-server#165]
Trying to get the syncing server(docker) running after migrating my files(all dockerized) to a new server, but the syncing server keeps restarting. No error logs in the mariadb database, can't seem to find much from the syncing server logs either.

Anything I can try? Here's the logs as said before:

```
NameError: wrong constant name INFO # "DEBUG" | "INFO" | "WARN" | "ERROR" | "FATAL"
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application/bootstrap.rb:61:in `const_get'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application/bootstrap.rb:61:in `block in <module:Bootstrap>'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
/syncing-server/config/environment.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate:ignore_concurrent => environment
(See full trace by running task with --trace)
Prestart Step 1/3 - Removing server lock
Prestart Step 2/3 - Migrating database
rake aborted!
```

**Comment by karolsojko** [comment]
This is related to https://github.com/standardnotes/syncing-server/issues/155

**Comment by karolsojko** [comment]
Please adjust your env file with the fixes applied in https://github.com/standardnotes/syncing-server/commit/e979405520a575916c4e68cc6689b11e3b3f0766 

Also make sure to switch your Docker image tag so that you are using `standardnotes/syncing-server:latest`
