### ISSUE TITLE
DB Errors when Running docker-compose

### ISSUE THREAD

**Issue by aashish108** [standardnotes/syncing-server#28]
Hi! When running docker-compose on my Synology, I get this error, would you know why this is occuring pls? Searched the net but not really sure :/

```rails aborted!
Mysql2::Error: Lost connection to MySQL server at 'handshake: reading inital communication packet', system error: 107
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `new'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `mysql2_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:761:in `new_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:805:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:784:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:745:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:502:in `checkout'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:376:in `connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_handling.rb:88:in `connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/schema_migration.rb:20:in `table_exists?'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/schema_migration.rb:24:in `create_table'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/migration.rb:1125:in `initialize'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/migration.rb:1007:in `new'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/migration.rb:1007:in `up'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/migration.rb:985:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/command.rb:46:in `invoke'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by johnny243** [comment]
Hey @aashish108, what is your OS version? 

Also, what are your machine specs?

**Comment by aashish108** [comment]
Hey, its a Synology DiskStation 916+. 8GB RAM, Intel Pentium N3710 quad-core 1.6GHz, burst up to 2.56GHz. THe rest of the specs are here: https://global.download.synology.com/download/Document/Hardware/DataSheet/DiskStation/16-year/DS916+/enu/Synology_DS916_Plus_Data_Sheet_enu.pdf

I couldn't get it to work on my Pi 4+, but that's another thread :)

Cheers!

**Comment by johnny243** [comment]
Did you set `DB_HOST` to `db` in your `.env` file?

Try clearing your DB volume for a fresh start:

`docker volume rm syncingserver_std_notes_db`

**Comment by rklasen** [comment]
Hi, I was having the same issue, and I think it's related to #27 and possibly other issues where the databse connection was the problem. *It can be fixed by removing comments from the env file on lines also containing config info.*

It seems the database root user is created with *no password* when there is a comment after the password in the `.env` file, which is the case in the default example:

```
DB_DATABASE=standard_notes_db
DB_USERNAME=std_notes_user
DB_PASSWORD=superSyncPassword # Please change this!
DB_ROOT_PASSWORD=superSyncPassword # Please change this!
```

This does not work because somewhere the lines containing comments are parsed incorrectly. I changed the passwords but left the `# Please change` comment in there and ran into the same issue. Once I removed them and left only the password, the database connection worked.

Best wishes!

**Comment by johnny243** [comment]
Thanks for reporting!
